--- name:default
# Opening of the beam along the device's Z direction
beam_height:
  rad: 35.deg
# Opening of the beam orthogonal to the device's Z direction
beam_width:
  rad: 3.deg
# Number of Bins
# bin_count: 1500
bin_count: 1000
# Enable/disable ping pong scanning mode
continuous: true
# Gain of the sonar (0.0 - 1.0)
gain: 0.35
# Left limit angle
left_limit:
  rad: -180.deg
# Step angle size
motor_step:
  # rad: 2.47.deg
  # rad: 1.8.deg
  rad: 0.225.deg
# Range of the sonar in meters (1.0 - 150.0)
range: 7.0
# Right limit angle
right_limit:
  rad: 179.99.deg
# Write shader image
write_shader_image: false
# attenuation_properties:
#   frequency: 10.0
