--- name:default
# # Number of Beams
# beam_count: 256
# # Opening of the beam along the device's Z direction
# beam_height:
#   rad: 20.deg
# # Opening of the beam orthogonal to the device's Z direction
# beam_width:
#   rad: 120.deg
# # Number of Bins
# bin_count: 600
# # Gain of the sonar (0.0 - 1.0)
# gain: 0.65
# # Set the virtual camera height
# height: 600
# # height: 1500
# # Range of the sonar in meters (1.0 - 150.0)
# range: 11.0
# # Write shader image
# write_shader_image: false

# --- name:similarity
# Number of Beams
beam_count: 256
# Opening of the beam along the device's Z direction
beam_height:
  rad: 20.deg
# Opening of the beam orthogonal to the device's Z direction
beam_width:
  rad: 120.deg
# Number of Bins
bin_count: 904
# Gain of the sonar (0.0 - 1.0)
gain: 0.40
# Set the virtual camera height
height: 600
# height: 1500
# Range of the sonar in meters (1.0 - 150.0)
range: 16.0
# Write shader image
write_shader_image: false
attenuation_properties:
  frequency: 500.0
